from __future__ import annotations

import json
from pathlib import Path


def create_todo_scaffold(workspace: str | Path) -> list[Path]:
    """Create the portfolio-grade, local-first Todo product used by ISEOL."""

    root = Path(workspace)
    files = {
        "index.html": """<!doctype html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#f6f7fb" />
    <meta name="description" content="Gleave가 만든 로컬 우선 Todo 워크스페이스" />
    <title>오늘의 Todo · Gleave</title>
    <link rel="icon" href="favicon.svg" />
    <link rel="stylesheet" href="src/shared/ui/styles.css" />
  </head>
  <body>
    <main id="app" aria-labelledby="page-title"></main>
    <script type="module" src="src/app/main.js"></script>
  </body>
</html>
""",
        "package.json": json.dumps(
            {
                "name": "gleave-todo-workspace",
                "private": True,
                "version": "1.0.0",
                "description": "A verified, local-first Todo workspace generated by Gleave.",
                "scripts": {"start": "python -m http.server 4173", "test:syntax": "node --check src/app/main.js"},
            },
            ensure_ascii=False,
            indent=2,
        ) + "\n",
        "favicon.svg": """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="18" fill="#111827"/><path d="m17 33 10 10 20-22" fill="none" stroke="#a7f3d0" stroke-linecap="round" stroke-linejoin="round" stroke-width="7"/></svg>
""",
        "README.md": """# 오늘의 Todo

Gleave와 ISEOL이 생성하고 독립 QA와 ClaimLatch 검증을 통과한 포트폴리오급 로컬 우선 Todo 워크스페이스입니다.

## 실행

```bash
python -m http.server 4173
```

브라우저에서 `http://localhost:4173`을 엽니다.

## 제품 기능

- Todo 생성·완료·수정·삭제
- 우선순위와 마감일 관리
- 전체·진행 중·완료·높은 우선순위 필터와 검색
- 오늘의 진행률·전체 통계·기한 초과 표시
- 브라우저 localStorage 기반 영속성
- 한국어 기본 UI, 키보드 접근성, 빈 상태·완료 상태
- 데스크톱·태블릿·모바일 반응형 대시보드

## 구조

Feature-Sliced Design 경계를 사용합니다: `app`, `pages`, `widgets`, `features`, `entities`, `shared`.

## 품질 기록

`DESIGN.md`, `PROJECT_LOG.md`, `QA_REPORT.json`, `RELEASE_MANIFEST.json`에 설계 결정, 트러블슈팅, 검증 근거와 릴리스 판정을 기록합니다.
""",
        "DESIGN.md": """# Todo 프로젝트 디자인

## 제품 의도

단순 목록이 아니라 사용자가 매일 열어보는 개인 작업 대시보드로 설계했습니다. 기본값은 정보 밀도를 낮추고 우선순위와 진행률을 빠르게 파악하도록 하며, 외부 서버 없이 로컬에서 즉시 사용할 수 있습니다.

## 디자인 기준

- Stayfolio 계열의 콘텐츠 우선 레이아웃과 넓은 여백
- 차분한 배경, 근흑색 본문, 민트색 완료 강조, 보라색 포커스
- 카드 기반 섹션과 일관된 spacing scale
- 320px부터 1440px까지 반응형 재배치
- 키보드 focus ring, 명확한 label, live region 제공

## 주요 결정

1. 외부 계정 없이 바로 사용하도록 localStorage를 선택했습니다.
2. Todo 모델에 priority와 dueDate를 포함해 실제 업무 흐름을 표현했습니다.
3. 목록과 통계를 분리해 FSD 경계를 명시하고 이후 캘린더·플러그인 확장을 준비했습니다.
4. 사용자 입력은 DOM textContent로 렌더링해 HTML 주입을 방지했습니다.
""",
        "PROJECT_LOG.md": """# 프로젝트 작업 기록

## 생성 기록

- 요청: Todo 앱 만들어줘
- 결정: 로컬 우선, 한국어 기본, FSD, 반응형 대시보드
- 검증: 독립 QA, UTF-8, JavaScript syntax, Todo E2E 시나리오, ClaimLatch release gate

## 트러블슈팅

- 최소 데모가 포트폴리오 수준의 정보 구조를 보여주지 못해 통계·검색·필터·수정·우선순위·마감일을 추가했습니다.
- 목록 렌더링은 사용자 입력을 `textContent`로 주입해 안전성을 확보했습니다.
""",
        "src/app/main.js": """import { renderTodoPage } from '../pages/todo-page/ui.js';

renderTodoPage(document.querySelector('#app'));
""",
        "src/entities/todo/model.js": """export const PRIORITIES = ['low', 'medium', 'high'];

export function createTodo(title, options = {}) {
  const normalized = title.trim();
  if (!normalized) return null;
  return {
    id: crypto.randomUUID(),
    title: normalized,
    completed: false,
    priority: PRIORITIES.includes(options.priority) ? options.priority : 'medium',
    dueDate: options.dueDate || '',
    tags: Array.isArray(options.tags) ? options.tags.filter(Boolean).slice(0, 3) : [],
    createdAt: new Date().toISOString(),
  };
}

export function toggleTodo(todo) {
  return { ...todo, completed: !todo.completed, completedAt: !todo.completed ? new Date().toISOString() : null };
}

export function updateTodo(todo, patch) {
  return { ...todo, ...patch, title: patch.title?.trim() || todo.title };
}

export function getTodoStats(todos) {
  const completed = todos.filter((todo) => todo.completed).length;
  const overdue = todos.filter((todo) => !todo.completed && todo.dueDate && todo.dueDate < new Date().toISOString().slice(0, 10)).length;
  return { total: todos.length, completed, active: todos.length - completed, overdue, completionRate: todos.length ? Math.round((completed / todos.length) * 100) : 0 };
}
""",
        "src/shared/lib/storage.js": """const KEY = 'gleave-todo-workspace-v1';

export function loadTodos() {
  try {
    const value = JSON.parse(localStorage.getItem(KEY) ?? '[]');
    return Array.isArray(value) ? value : [];
  } catch { return []; }
}

export function saveTodos(todos) { localStorage.setItem(KEY, JSON.stringify(todos)); }
""",
        "src/features/todo-create/ui.js": """import { createTodo } from '../../entities/todo/model.js';

export function createTodoFromInput(input, options = {}) {
  const todo = createTodo(input.value, options);
  if (todo) input.value = '';
  return todo;
}
""",
        "src/features/todo-toggle/ui.js": """import { toggleTodo } from '../../entities/todo/model.js';

export function toggleTodoAt(todos, id) { return todos.map((todo) => todo.id === id ? toggleTodo(todo) : todo); }
""",
        "src/features/todo-edit/ui.js": """import { updateTodo } from '../../entities/todo/model.js';

export function updateTodoAt(todos, id, patch) { return todos.map((todo) => todo.id === id ? updateTodo(todo, patch) : todo); }
""",
        "src/features/todo-filter/ui.js": """export function filterTodos(todos, filter, query = '') {
  const normalizedQuery = query.trim().toLowerCase();
  return todos.filter((todo) => {
    const matchesFilter = filter === 'all' || (filter === 'active' && !todo.completed) || (filter === 'completed' && todo.completed) || (filter === 'high' && todo.priority === 'high' && !todo.completed);
    const matchesQuery = !normalizedQuery || todo.title.toLowerCase().includes(normalizedQuery) || todo.tags?.some((tag) => tag.toLowerCase().includes(normalizedQuery));
    return matchesFilter && matchesQuery;
  });
}
""",
        "src/widgets/todo-stats/ui.js": """export function renderTodoStats(root, stats) {
  root.querySelector('[data-stat=total]').textContent = stats.total;
  root.querySelector('[data-stat=active]').textContent = stats.active;
  root.querySelector('[data-stat=completed]').textContent = stats.completed;
  root.querySelector('[data-stat=overdue]').textContent = stats.overdue;
  root.querySelector('[data-progress-value]').style.width = `${stats.completionRate}%`;
  root.querySelector('[data-progress-label]').textContent = `${stats.completionRate}% 완료`;
}
""",
        "src/widgets/todo-list/ui.js": """const priorityLabels = { low: '낮음', medium: '보통', high: '높음' };

export function renderTodoList(list, todos, handlers) {
  list.replaceChildren();
  for (const todo of todos) {
    const item = document.createElement('li');
    item.className = `task-card${todo.completed ? ' task-card--done' : ''}`;
    item.dataset.taskId = todo.id;
    const check = document.createElement('input');
    check.type = 'checkbox'; check.checked = todo.completed;
    check.setAttribute('aria-label', `${todo.title} 완료 처리`);
    check.addEventListener('change', () => handlers.toggle(todo.id));
    const title = document.createElement('span'); title.className = 'task-card__title'; title.textContent = todo.title;
    const content = document.createElement('div'); content.className = 'task-card__content'; content.append(title);
    if (todo.dueDate) { const due = document.createElement('span'); due.className = 'task-card__meta'; due.textContent = `마감 ${todo.dueDate}`; content.append(due); }
    const priority = document.createElement('span'); priority.className = `priority priority--${todo.priority}`; priority.textContent = priorityLabels[todo.priority] || priorityLabels.medium; content.append(priority);
    const edit = document.createElement('button'); edit.type = 'button'; edit.className = 'icon-button'; edit.dataset.edit = todo.id; edit.setAttribute('aria-label', `${todo.title} 수정`); edit.textContent = '수정'; edit.addEventListener('click', () => handlers.edit(todo.id));
    const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'icon-button icon-button--danger'; remove.dataset.delete = todo.id; remove.setAttribute('aria-label', `${todo.title} 삭제`); remove.textContent = '삭제'; remove.addEventListener('click', () => handlers.remove(todo.id));
    const actions = document.createElement('div'); actions.className = 'task-card__actions'; actions.append(edit, remove);
    item.append(check, content, actions); list.append(item);
  }
}
""",
        "src/pages/todo-page/ui.js": """import { createTodoFromInput } from '../../features/todo-create/ui.js';
import { toggleTodoAt } from '../../features/todo-toggle/ui.js';
import { updateTodoAt } from '../../features/todo-edit/ui.js';
import { filterTodos } from '../../features/todo-filter/ui.js';
import { getTodoStats } from '../../entities/todo/model.js';
import { loadTodos, saveTodos } from '../../shared/lib/storage.js';
import { renderTodoList } from '../../widgets/todo-list/ui.js';
import { renderTodoStats } from '../../widgets/todo-stats/ui.js';

export function renderTodoPage(root) {
  let todos = loadTodos(); let filter = 'all'; let query = ''; let editingId = null;
  root.innerHTML = `<div class="shell"><aside class="sidebar" aria-label="주요 메뉴"><div class="brand"><span class="brand__mark">G</span><span>Gleave</span></div><p class="sidebar__label">WORKSPACE</p><nav class="nav-list"><button class="nav-item nav-item--active" type="button">오늘의 Todo</button><button class="nav-item" type="button" disabled>프로젝트 준비 중</button></nav><div class="sidebar__footer"><span class="status-dot"></span> 로컬에서 안전하게 저장됨</div></aside><section class="workspace"><header class="topbar"><div><p class="eyebrow">PERSONAL WORKSPACE</p><h1 id="page-title">오늘의 Todo</h1></div><div class="avatar" aria-label="사용자">U</div></header><div class="hero"><div><p class="hero__kicker">좋은 하루의 시작</p><h2>오늘 해야 할 일을<br><em>명확하게</em> 정리하세요.</h2><p class="hero__copy">작은 실행을 기록하고, 완료한 순간을 한눈에 확인해보세요.</p></div><div class="hero__shape" aria-hidden="true">✦</div></div><section class="stats" aria-label="Todo 통계"><article class="stat-card"><span>전체 작업</span><strong data-stat="total">0</strong><small>등록된 모든 작업</small></article><article class="stat-card"><span>진행 중</span><strong data-stat="active">0</strong><small>아직 남은 작업</small></article><article class="stat-card"><span>완료</span><strong data-stat="completed">0</strong><small>해낸 작업</small></article><article class="stat-card stat-card--alert"><span>기한 초과</span><strong data-stat="overdue">0</strong><small>확인이 필요한 작업</small></article></section><section class="progress-panel" aria-label="완료율"><div class="progress-panel__top"><div><span class="section-label">이번 주 진행률</span><strong data-progress-label>0% 완료</strong></div><span class="progress-badge">LOCAL FIRST</span></div><div class="progress-track"><div class="progress-value" data-progress-value></div></div></section><section class="tasks-panel" aria-labelledby="tasks-heading"><div class="section-heading"><div><span class="section-label">MY TASKS</span><h2 id="tasks-heading">작업 목록</h2></div><span class="task-count" data-count>0개</span></div><form class="create-form" id="todo-form"><label class="sr-only" for="todo-input">새 Todo</label><input id="todo-input" placeholder="새로운 작업을 입력하세요" autocomplete="off" required><select id="priority-input" aria-label="우선순위"><option value="medium">보통 우선순위</option><option value="high">높은 우선순위</option><option value="low">낮은 우선순위</option></select><input id="due-input" type="date" aria-label="마감일"><button class="primary-button" type="submit">+ 작업 추가</button></form><div class="toolbar"><div class="filters" role="group" aria-label="작업 필터"><button type="button" class="filter-button filter-button--active" data-filter="all">전체</button><button type="button" class="filter-button" data-filter="active">진행 중</button><button type="button" class="filter-button" data-filter="completed">완료</button><button type="button" class="filter-button" data-filter="high">높은 우선순위</button></div><label class="search-box"><span aria-hidden="true">⌕</span><input id="search-input" placeholder="작업 검색" aria-label="작업 검색"></label></div><p class="empty" data-empty hidden>조건에 맞는 작업이 없습니다.<br><small>새 작업을 추가하거나 필터를 바꿔보세요.</small></p><ul class="task-list" id="todo-list" aria-live="polite"></ul></section><footer class="footer-note">Gleave Project · 모든 데이터는 이 기기에 저장됩니다.</footer></section></div><dialog id="edit-dialog" class="edit-dialog"><form method="dialog" id="edit-form"><div class="dialog__top"><div><span class="section-label">EDIT TASK</span><h2>작업 수정</h2></div><button class="close-button" value="cancel" aria-label="닫기">×</button></div><label for="edit-title">작업 이름</label><input id="edit-title" required><label for="edit-priority">우선순위</label><select id="edit-priority"><option value="low">낮음</option><option value="medium">보통</option><option value="high">높음</option></select><label for="edit-due">마감일</label><input id="edit-due" type="date"><div class="dialog__actions"><button value="cancel" class="secondary-button">취소</button><button value="default" class="primary-button">저장하기</button></div></form></dialog>`;
  const form = root.querySelector('#todo-form'); const input = root.querySelector('#todo-input'); const priorityInput = root.querySelector('#priority-input'); const dueInput = root.querySelector('#due-input'); const list = root.querySelector('#todo-list'); const empty = root.querySelector('[data-empty]'); const search = root.querySelector('#search-input'); const dialog = root.querySelector('#edit-dialog'); const editForm = root.querySelector('#edit-form');
  const paint = () => { const visible = filterTodos(todos, filter, query); renderTodoList(list, visible, { toggle: (id) => { todos = toggleTodoAt(todos, id); saveTodos(todos); paint(); }, remove: (id) => { todos = todos.filter((todo) => todo.id !== id); saveTodos(todos); paint(); }, edit: (id) => openEditor(id) }); renderTodoStats(root, getTodoStats(todos)); root.querySelector('[data-count]').textContent = `${visible.length}개`; empty.hidden = visible.length > 0; };
  const openEditor = (id) => { const todo = todos.find((item) => item.id === id); if (!todo) return; editingId = id; root.querySelector('#edit-title').value = todo.title; root.querySelector('#edit-priority').value = todo.priority; root.querySelector('#edit-due').value = todo.dueDate || ''; dialog.showModal(); };
  form.addEventListener('submit', (event) => { event.preventDefault(); const todo = createTodoFromInput(input, { priority: priorityInput.value, dueDate: dueInput.value }); if (todo) { todos = [todo, ...todos]; saveTodos(todos); dueInput.value = ''; priorityInput.value = 'medium'; paint(); input.focus(); } });
  root.querySelectorAll('[data-filter]').forEach((button) => button.addEventListener('click', () => { filter = button.dataset.filter; root.querySelectorAll('[data-filter]').forEach((item) => item.classList.toggle('filter-button--active', item === button)); paint(); }));
  search.addEventListener('input', () => { query = search.value; paint(); });
  editForm.addEventListener('submit', (event) => { if (event.submitter?.value !== 'default' || editingId === null) return; event.preventDefault(); todos = updateTodoAt(todos, editingId, { title: root.querySelector('#edit-title').value, priority: root.querySelector('#edit-priority').value, dueDate: root.querySelector('#edit-due').value }); saveTodos(todos); dialog.close(); editingId = null; paint(); });
  paint();
}
""",
        "src/shared/ui/styles.css": """:root { color: #172033; background: #f6f7fb; font-family: Inter, Pretendard, system-ui, sans-serif; --ink: #172033; --muted: #7b8497; --line: #e6eaf1; --surface: #fff; --accent: #7367f0; --mint: #b8f0d0; --danger: #df6b76; }
* { box-sizing: border-box; } body { margin: 0; min-width: 320px; background: #f6f7fb; } button, input, select { font: inherit; } button { cursor: pointer; }
.shell { display: flex; min-height: 100vh; } .sidebar { width: 240px; background: #fff; border-right: 1px solid var(--line); padding: 32px 20px 24px; display: flex; flex-direction: column; } .brand { display: flex; align-items: center; gap: 10px; font-size: 20px; font-weight: 800; letter-spacing: -.04em; margin: 0 8px 72px; } .brand__mark { width: 34px; height: 34px; display: grid; place-items: center; border-radius: 11px; color: #fff; background: var(--ink); } .sidebar__label, .section-label, .eyebrow, .hero__kicker { font-size: 11px; letter-spacing: .12em; font-weight: 700; color: var(--muted); } .sidebar__label { margin: 0 12px 12px; } .nav-list { display: grid; gap: 8px; } .nav-item { border: 0; border-radius: 12px; padding: 13px 14px; background: transparent; color: var(--muted); text-align: left; font-weight: 650; } .nav-item--active { color: var(--ink); background: #eef0ff; } .nav-item:disabled { cursor: not-allowed; opacity: .55; } .sidebar__footer { margin-top: auto; color: var(--muted); font-size: 12px; display: flex; align-items: center; gap: 8px; } .status-dot { width: 8px; height: 8px; border-radius: 50%; background: #48c985; }
.workspace { width: min(1200px, 100%); padding: 34px 48px 46px; margin: 0 auto; } .topbar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 36px; } .eyebrow { margin: 0 0 8px; } h1, h2, p { margin-top: 0; } h1 { margin-bottom: 0; font-size: clamp(28px, 4vw, 42px); letter-spacing: -.06em; } .avatar { width: 40px; height: 40px; display: grid; place-items: center; border-radius: 50%; background: var(--ink); color: #fff; font-weight: 800; }
.hero { display: flex; justify-content: space-between; align-items: center; min-height: 232px; padding: 34px 42px; margin-bottom: 24px; border-radius: 24px; overflow: hidden; background: linear-gradient(110deg, #e7e8ff, #f1f3ff 58%, #e2f6eb); position: relative; } .hero__kicker { margin-bottom: 12px; color: #6560c8; } .hero h2 { font-size: clamp(28px, 4vw, 48px); line-height: 1.12; letter-spacing: -.07em; margin-bottom: 14px; } .hero h2 em { color: #5e5ad0; font-style: normal; } .hero__copy { color: #69748a; margin-bottom: 0; } .hero__shape { font-size: 126px; line-height: 1; color: #8078eb; transform: rotate(18deg); opacity: .5; margin-right: 8%; }
.stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; margin-bottom: 18px; } .stat-card { padding: 20px; border: 1px solid var(--line); border-radius: 18px; background: var(--surface); } .stat-card span, .stat-card small { display: block; color: var(--muted); font-size: 12px; } .stat-card strong { display: block; margin: 9px 0 5px; color: var(--ink); font-size: 32px; letter-spacing: -.05em; } .stat-card--alert strong { color: var(--danger); }
.progress-panel, .tasks-panel { padding: 26px; border: 1px solid var(--line); border-radius: 20px; background: var(--surface); margin-bottom: 18px; } .progress-panel__top, .section-heading, .toolbar { display: flex; justify-content: space-between; align-items: center; gap: 16px; } .progress-panel__top strong { display: block; margin-top: 7px; font-size: 18px; } .progress-badge { padding: 6px 10px; border-radius: 100px; background: #e4faed; color: #278756; font-size: 10px; font-weight: 800; letter-spacing: .08em; } .progress-track { height: 10px; background: #eef0f5; border-radius: 100px; margin-top: 20px; overflow: hidden; } .progress-value { width: 0; height: 100%; border-radius: inherit; background: linear-gradient(90deg, #7d70ee, #9de2b9); transition: width .3s ease; }
.section-heading { margin-bottom: 22px; } .section-heading h2 { margin: 6px 0 0; font-size: 24px; letter-spacing: -.05em; } .task-count { color: var(--muted); font-size: 13px; } .create-form { display: grid; grid-template-columns: minmax(180px, 1fr) 145px 145px auto; gap: 10px; margin-bottom: 22px; } .create-form input, .create-form select, .search-box input, .edit-dialog input, .edit-dialog select { min-width: 0; width: 100%; border: 1px solid var(--line); border-radius: 12px; padding: 13px 14px; color: var(--ink); background: #fbfcfe; outline: none; } input:focus, select:focus, button:focus-visible { border-color: var(--accent); outline: 3px solid #dcd9ff; outline-offset: 1px; } .primary-button, .secondary-button { border: 0; border-radius: 12px; padding: 0 17px; min-height: 46px; font-weight: 750; } .primary-button { color: #fff; background: var(--ink); } .secondary-button { color: var(--ink); background: #edf0f5; }
.toolbar { padding-bottom: 18px; border-bottom: 1px solid var(--line); } .filters { display: flex; flex-wrap: wrap; gap: 6px; } .filter-button { border: 0; border-radius: 9px; padding: 8px 11px; color: var(--muted); background: transparent; font-size: 12px; font-weight: 700; } .filter-button--active { color: var(--ink); background: #eef0ff; } .search-box { display: flex; align-items: center; gap: 7px; padding: 0 10px; border: 1px solid var(--line); border-radius: 10px; color: var(--muted); } .search-box input { border: 0; width: 140px; padding: 9px 2px; background: transparent; outline: none; }
.task-list { display: grid; gap: 10px; padding: 18px 0 0; margin: 0; list-style: none; } .task-card { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; gap: 14px; align-items: center; padding: 17px; border: 1px solid var(--line); border-radius: 15px; transition: border-color .2s, transform .2s, box-shadow .2s; } .task-card:hover { border-color: #cbd0ec; transform: translateY(-1px); box-shadow: 0 7px 20px rgba(38, 45, 74, .06); } .task-card input { width: 18px; height: 18px; accent-color: #68c994; } .task-card__content { min-width: 0; display: flex; align-items: center; gap: 10px; flex-wrap: wrap; } .task-card__title { font-weight: 700; overflow-wrap: anywhere; } .task-card--done .task-card__title { color: #9aa2b2; text-decoration: line-through; } .task-card__meta { color: var(--muted); font-size: 11px; } .priority { padding: 4px 8px; border-radius: 7px; font-size: 10px; font-weight: 800; } .priority--high { color: #c34c5b; background: #fff0f1; } .priority--medium { color: #837029; background: #fff8da; } .priority--low { color: #43825d; background: #e9f8ef; } .task-card__actions { display: flex; gap: 4px; } .icon-button { border: 0; padding: 7px; border-radius: 8px; color: #657087; background: transparent; font-size: 12px; } .icon-button:hover { background: #f1f3f7; } .icon-button--danger { color: var(--danger); } .empty { padding: 44px 16px 24px; color: var(--muted); text-align: center; line-height: 1.8; } .empty small { font-size: 12px; } .footer-note { color: var(--muted); font-size: 11px; text-align: right; }
.edit-dialog { width: min(430px, calc(100% - 32px)); padding: 26px; border: 0; border-radius: 20px; box-shadow: 0 24px 80px rgba(23, 32, 51, .2); color: var(--ink); } .edit-dialog::backdrop { background: rgba(23, 32, 51, .35); backdrop-filter: blur(3px); } .edit-dialog label { display: block; margin: 16px 0 7px; color: var(--muted); font-size: 12px; font-weight: 700; } .dialog__top { display: flex; justify-content: space-between; align-items: start; } .dialog__top h2 { margin: 8px 0 0; } .close-button { border: 0; background: transparent; font-size: 26px; color: var(--muted); } .dialog__actions { display: flex; justify-content: end; gap: 8px; margin-top: 22px; } .dialog__actions button { min-height: 42px; } .sr-only { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0; }
@media (max-width: 980px) { .sidebar { width: 190px; } .workspace { padding: 28px; } .create-form { grid-template-columns: 1fr 1fr; } .create-form input:first-of-type { grid-column: span 2; } .create-form .primary-button { min-height: 46px; } }
@media (max-width: 680px) { .shell { display: block; } .sidebar { width: auto; padding: 16px 18px; border-right: 0; border-bottom: 1px solid var(--line); } .brand { margin: 0 0 14px; } .sidebar__label, .sidebar__footer { display: none; } .nav-list { display: flex; } .nav-item { padding: 9px 11px; } .workspace { padding: 22px 16px 30px; } .topbar { margin-bottom: 22px; } .hero { min-height: 215px; padding: 25px; } .hero__shape { font-size: 82px; margin-right: 0; } .stats { grid-template-columns: repeat(2, 1fr); } .progress-panel, .tasks-panel { padding: 19px; } .toolbar { align-items: stretch; flex-direction: column; } .search-box input { width: 100%; } .create-form { display: flex; flex-direction: column; } .create-form input:first-of-type { min-height: 48px; } .create-form .primary-button { min-height: 48px; } .task-card { grid-template-columns: auto minmax(0, 1fr); } .task-card__actions { grid-column: 2; justify-content: end; } .footer-note { text-align: center; } }
@media (max-width: 390px) { .hero h2 { font-size: 28px; } .hero__copy { font-size: 12px; } .hero__shape { display: none; } .stat-card { padding: 15px; } .stat-card strong { font-size: 26px; } .filters { gap: 2px; } .filter-button { padding: 7px 8px; } }
""",
        "tests/e2e/todo-flow.md": """# Todo E2E 시나리오

1. 앱을 연다. 대시보드와 사이드바·통계·작업 목록이 보인다.
2. 작업 이름, 우선순위, 마감일을 입력하고 추가한다.
3. 작업이 목록과 전체/진행 중 통계에 반영되는지 확인한다.
4. 완료 처리하고 진행률과 완료 통계가 갱신되는지 확인한다.
5. 검색창과 전체·진행 중·완료·높은 우선순위 필터를 확인한다.
6. 수정 대화상자에서 이름·우선순위·마감일을 변경한다.
7. 새로고침 후 작업·완료·필터 데이터가 유지되는지 확인한다.
8. 삭제하고 목록·통계가 갱신되는지 확인한다.
9. 키보드 focus와 접근성 label을 확인한다.
10. 반응형 기준 320px, 390px, 768px, 1440px에서 레이아웃과 읽기 순서를 확인한다.
""",
    }
    created: list[Path] = []
    for relative, content in files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(content, encoding="utf-8", newline="\n")
            created.append(path)
    return created
